### ISSUE TITLE
tensorflow

### ISSUE THREAD

**Issue by Thexiyang** [chklovski/CheckM2#14]
Hi I followed the protocol to install the software and came across the following warning message. Is everything fine? Should I just ignore it? 

: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`

**Comment by chklovski** [comment]
This may be due to using a different version of tensorflow. Release [1.0.0](https://github.com/chklovski/CheckM2/releases/tag/1.0.0) and onwards has constrained the set of tensorflow versions that should be used in the checkm2.yaml file and are known to work well with checkm2. Please let me know if this is still an issue with a new environment and the latest release.
