### ISSUE TITLE
Assessing the quality of viral bins

### ISSUE THREAD

**Issue by quliping** [chklovski/CheckM2#27]
Recently, I'm working on viral metagenomics. I identified viral contigs using virsorter2 and then performed binning using vRhyme. Finally I obtained some viral MAGs (vMAGs). CheckV seems could only assess the quality of single viral contig, is checkM2 worked for vMAGs?

**Comment by chklovski** [comment]
Hi,
 
In its current state CheckM2 has not been trained on viruses and will not give accurate predictions on viral bins.

**Comment by LeonardoMorenoG** [comment]
Hello quliping,

if you are interested in the quality assessment of your "vMAGs" (formally called UViGs, from "Uncultivated Viral Genomes") you can use a tool called **CheckV** (https://doi.org/10.1038/s41587-020-00774-7).

Since you mentioned you're new on viral metagenomics, I would like to recommend you the following review  on computational tools for the analysis of uncultivated ghage genomes: https://doi.org/10.1128/mmbr.00004-21
