### ISSUE TITLE
There was a problem installing the database

### ISSUE THREAD

**Issue by ylei14** [chklovski/CheckM2#72]
Could you please provide the download link of checkm2 database? Unable to use checkm2 --download database to download database due to network reasons.

cheers!

**Comment by ylei14** [comment]
sry, checkm2 database --download

**Comment by cug21yu** [comment]
I have the same error when run "checkm2 database --download --path /home/software/CheckM2". Please let me know if you have any solution. Thanks.

Traceback (most recent call last):
  File "/home/public-230608/mambaforge/envs/checkm2/bin/checkm2", line 280, in <module>
    fileManager.DiamondDB().download_database(args.path)
  File "/home/public-230608/mambaforge/envs/checkm2/lib/python3.8/site-packages/checkm2/fileManager.py", line 127, in download_database
    backpack_downloader.download_and_extract(download_location, DOI, progress_bar=True, no_check_version=False)
  File "/home/public-230608/mambaforge/envs/checkm2/lib/python3.8/site-packages/checkm2/zenodo_backpack.py", line 46, in download_and_extract
    recordID = self._retrieve_record_ID(DOI)
  File "/home/public-230608/mambaforge/envs/checkm2/lib/python3.8/site-packages/checkm2/zenodo_backpack.py", line 166, in _retrieve_record_ID
    raise ZenodoConnectionException('Connection error: {}'.format(e))
checkm2.zenodo_backpack.ZenodoConnectionException: Connection error: HTTPSConnectionPool(host='zenodo.org', port=443): Max retries exceeded with url: /record/5571251 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ffb2d0cb460>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by cug21yu** [comment]
Is this the download link of checkm2 database? I would have a try.
(https://zenodo.org/record/5571251/files/checkm2_database.tar.gz?download=1).

**Comment by cug21yu** [comment]
> Is this the download link of checkm2 database? I would have a try. (https://zenodo.org/record/5571251/files/checkm2_database.tar.gz?download=1).

checkm2 now works for me with the above database.

**Comment by chklovski** [comment]
Thanks for that, I will add the link to the README so people can access it easier.
