### ISSUE TITLE
Small test diamond db

### ISSUE THREAD

**Issue by mberacochea** [chklovski/CheckM2#81]
Hi,

Thank you for checkm2; it's very helpful. We are currently working on an nf-core module for this tool and I was wondering if it's possible to create a smaller Diamond database for a unit test. Could you please provide some guidance?

Cheers

**Comment by chklovski** [comment]
Hi, 

What's the purpose of using a smaller db for the testcase? Currently CheckM2 forces a checksum on the database it uses and throws an error if it's not the expected database for a given CheckM2 version. Because the training & testing is performed using the same database, altering the database can alter the expected distribution of annotations for the genomes CheckM2 has been trained on, leading to inaccurate predictions. 

An example of this: If you were to simply filter the existing database (uniref100 annotated with kegg ID's) down to uniref50, and run existing CheckM2 models, predictions of completeness & contamination change. In edge cases, for example for highly novel genomes coming from highly reduced lineages, they can lose as much as 10-15% completeness. 

Retraining the CheckM2 machine learning models on synthetic genomes annotated using the new database would likely get around this by changing expected distribution of annotations, but you would need to re-generate annotation for all ~1+ million synthetic genomes CheckM2 uses in its database in order to retrain the models, and it wouldn't be reproducible for other users on stock CheckM2 database & models. 

We can do this centrally for a major release if there's a good benefit of e.g. a newer database with better annotations, but I'm not sure that would be useful for your testcase.

**Comment by mberacochea** [comment]
Hi @chklovski,

We've created a reusable CheckM2 Nextflow module at https://github.com/EBI-Metagenomics/nf-modules/blob/modules/checkm2/modules/ebi-metagenomics/checkm2/checkm2/main.nf. As a part of that development, we want to add some unit tests, which will run in Github Actions. For unit tests, the size of the CheckM2 db is problematic, which is why I've reached out to you.

I thought it might not be feasible to create a smaller DB without significant effort. We will find a way around it, probably by running CheckM2 tests on our in-house HPC cluster.

Anyway, thank you for the insights :).

Cheers
