### ISSUE TITLE
How to remove the contamination sequence from MAGs

### ISSUE THREAD

**Issue by quliping** [chklovski/CheckM2#90]
Hello, both checkM1 and checkM2 are excellent softwares to estimate the quality of MAGs. However, is there any way to remove the contamination sequences in the MAG? It seems that checkM1/checkM2 could only tell us the quality of a MAG.

**Comment by chklovski** [comment]
I don't think it should be CheckM2's job to remove contamination, as that is likely to just bias fitting MAG composition to CheckM2 scores instead of using proper binning metric (coverage, tetranucleotide identity, etc). If you're after tools to improve MAGs, you could try something like GUNC or MAGpurify.

**Comment by quliping** [comment]
Thanks for your suggestion, I will try MAGpurify and GUNC.
